#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-

# Copyright _!_
#
# License _!_
#
# Original author: Ansgar Grunseid

import sys

def generatePassword():
    return 'lolpasswordlol'

def main():
    password = generatePassword()
    print(password, end='')

if __name__ == '__main__':
    main()
